GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FhZCIsImlhdCI6MTczNTAzNzIzNX0.vR9OQdzMyoP0BXUslTGTQOFbqoz5UtH7Bvxf8B3vH98
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "Saad"
}